CREATE TABLE IF NOT EXISTS ads_accounts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pipocine_user_id BIGINT UNSIGNED NULL,
    brand_name VARCHAR(120) NOT NULL,
    cnpj CHAR(14) NULL,
    email VARCHAR(190) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    logo_url VARCHAR(500) NULL,
    website_url VARCHAR(500) NULL,
    contact_name VARCHAR(120) NULL,
    phone_e164 VARCHAR(24) NULL,
    industry VARCHAR(80) NULL,
    company_size ENUM('solo','small','medium','large') NULL,
    business_description VARCHAR(280) NULL,
    onboarding_completed_at DATETIME NULL,
    first_ad_demo_claimed_at DATETIME NULL,
    status ENUM('active','pending_review','suspended') NOT NULL DEFAULT 'active',
    email_verified_at DATETIME NULL,
    last_login_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ads_accounts_email (email),
    UNIQUE KEY uq_ads_accounts_cnpj (cnpj),
    UNIQUE KEY uq_ads_accounts_pipocine_user (pipocine_user_id),
    KEY idx_ads_accounts_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ads_campaigns (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ads_account_id BIGINT UNSIGNED NOT NULL,
    draft_token CHAR(64) NULL,
    cdn_token CHAR(64) NULL,
    name VARCHAR(140) NOT NULL,
    description VARCHAR(500) NULL,
    creative_type ENUM('image','video') NOT NULL,
    creative_url VARCHAR(500) NOT NULL DEFAULT '',
    creative_duration_seconds SMALLINT UNSIGNED NULL,
    creative_mime_type VARCHAR(80) NULL,
    media_provider ENUM('imgbb','vids_st') NULL,
    media_provider_file_id VARCHAR(120) NULL,
    original_filename VARCHAR(255) NULL,
    file_size_bytes BIGINT UNSIGNED NULL,
    redirect_url VARCHAR(500) NULL,
    can_skip TINYINT(1) NOT NULL DEFAULT 1,
    price_cents INT UNSIGNED NOT NULL DEFAULT 1000,
    is_demo TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('draft','awaiting_payment','pending_review','in_review','changes_requested','approved','active','paused','rejected','finished') NOT NULL DEFAULT 'draft',
    submitted_at DATETIME NULL,
    reviewed_at DATETIME NULL,
    review_notes VARCHAR(500) NULL,
    review_lock_admin_id INT NULL,
    review_lock_expires_at DATETIME NULL,
    review_started_at DATETIME NULL,
    reviewed_by_admin_id INT NULL,
    approved_at DATETIME NULL,
    activated_at DATETIME NULL,
    rejected_at DATETIME NULL,
    changes_requested_at DATETIME NULL,
    starts_at DATETIME NULL,
    ends_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_ads_campaigns_account FOREIGN KEY (ads_account_id) REFERENCES ads_accounts(id),
    UNIQUE KEY uq_ads_campaigns_draft_token (draft_token),
    UNIQUE KEY uq_ads_campaigns_cdn_token (cdn_token),
    KEY idx_ads_campaigns_account_status (ads_account_id, status),
    KEY idx_ads_campaigns_review_queue (status, submitted_at),
    KEY idx_ads_campaigns_review_lock (review_lock_admin_id, review_lock_expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ads_campaign_status_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    campaign_id BIGINT UNSIGNED NOT NULL,
    from_status VARCHAR(40) NULL,
    to_status VARCHAR(40) NOT NULL,
    note VARCHAR(255) NULL,
    actor_type ENUM('system','advertiser','admin') NOT NULL DEFAULT 'system',
    actor_admin_id INT NULL,
    public_note VARCHAR(500) NULL,
    internal_note VARCHAR(500) NULL,
    metadata JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ads_campaign_status_events_campaign FOREIGN KEY (campaign_id) REFERENCES ads_campaigns(id),
    KEY idx_ads_campaign_status_events_campaign (campaign_id, created_at),
    KEY idx_ads_campaign_status_events_actor (actor_type, actor_admin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ads_daily_metrics (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    campaign_id BIGINT UNSIGNED NOT NULL,
    metric_date DATE NOT NULL,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    conversions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    unique_reach BIGINT UNSIGNED NOT NULL DEFAULT 0,
    completed_views BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_ads_daily_metrics_campaign FOREIGN KEY (campaign_id) REFERENCES ads_campaigns(id),
    UNIQUE KEY uq_ads_daily_metrics_campaign_date (campaign_id, metric_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ads_audit_log (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ads_account_id BIGINT UNSIGNED NULL,
    actor_user_id BIGINT UNSIGNED NULL,
    action VARCHAR(120) NOT NULL,
    context_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_ads_audit_account (ads_account_id),
    KEY idx_ads_audit_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
